# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 776a0881379778f166e9cf67badc8b2be4e345bd10d32dd9bddb98d0ef0ae65256d9df64e8b72cf3e7bcd92831cb2714370db4bcabd8f450104311f18f4d4376

test:
  secret_key_base: e2777385c0bd840a7254db2fdc615067b7acbc32e3e759cdbcbdbfec5248c40a76a2e790e5c749c8787fd7e24c703b528746b1a2c5351bfd0c2cf5c70ed05c55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
